# Generated by Django 5.0.6 on 2024-06-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Чоловіки'), ('women', 'Жінки')], default='men', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('everyday', 'Повсякденне'), ('sports', 'Спортивне'), ('luxury', 'Люкс'), ('casual', 'Кежуал'), ('formal', 'Офіційне')], max_length=10),
        ),
    ]
