# Generated by Django 5.0.6 on 2024-06-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Не вказано', max_length=255),
            preserve_default=False,
        ),
    ]
